#!/usr/bin/env php

<?php

use GorkaLaucirica\RedirectChecker\Infrastructure\Ui\Cli\Symfony\CheckRedirectionFromYamlCommand;
use Symfony\Component\Console\Application;

require_once __DIR__ . '/../../../../../../../vendor/autoload.php';

$application = new Application();

$application->add(new CheckRedirectionFromYamlCommand());

$application->run();
