#!/usr/bin/env php

<?php

use GorkaLaucirica\RedirectChecker\Infrastructure\Ui\Cli\Symfony\CheckRedirectionFromYamlCommand;
use Symfony\Component\Console\Application;

if (is_file($autoload = __DIR__ . '/../../../../../../../../../../vendor/autoload.php')) {
    require $autoload;
} elseif (is_file($autoload = __DIR__ . '/../../../../../../../vendor/autoload.php')) {
    require $autoload;
} else {
    fwrite(STDERR,
        'You must set up the project dependencies, run the following commands:' . PHP_EOL .
        'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
        'php composer.phar install' . PHP_EOL
    );
    exit(1);
}

$application = new Application();

$application->add(new CheckRedirectionFromYamlCommand());

$application->run();
